# Generated by Django 5.0 on 2023-12-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Category', models.IntegerField(null=True, unique=True)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID_Post', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Date_Published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usernew',
            fields=[
                ('ID_Usernew', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Comment', models.IntegerField(default=0, null=True, unique=True)),
                ('Content', models.CharField(max_length=255)),
                ('Date_Posted', models.DateField()),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.usernew')),
            ],
        ),
    ]
